# Generated by Django 5.1.15 on 2026-07-13 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nova conversa', max_length=200)),
                ('arquivada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('user', 'Usuário'), ('assistente', 'Assistente')], max_length=12)),
                ('texto', models.TextField()),
                ('assunto', models.CharField(blank=True, default='', max_length=20)),
                ('on_topic', models.BooleanField(default=True)),
                ('disclaimer', models.TextField(blank=True, default='')),
                ('fontes', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='conversas.conversa')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['user', '-atualizado_em'], name='conversas_c_user_id_b4504a_idx'),
        ),
    ]
