# Generated by Django 5.1.15 on 2026-07-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default='', help_text='Foto do perfil (Google/Clerk).'),
        ),
    ]
