# Generated by Django 5.1.15 on 2026-07-12 22:28

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoDuvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(choices=[('direito', 'Direito eleitoral'), ('contabilidade', 'Contabilidade eleitoral'), ('impulsionamento', 'Impulsionamento eleitoral')], db_index=True, max_length=20)),
                ('pergunta_canonica', models.TextField(help_text='Pergunta representante do grupo.')),
                ('texto_normalizado', models.TextField(help_text='Chave do match exato (normalizada).')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('frequencia', models.PositiveIntegerField(default=1, help_text='Total de ocorrências.')),
                ('ocorrencias_exatas', models.PositiveIntegerField(default=0, help_text='Perguntas idênticas.')),
                ('variacoes', models.PositiveIntegerField(default=0, help_text='Entradas por sentido próximo.')),
                ('primeira_ocorrencia', models.DateTimeField(auto_now_add=True)),
                ('ultima_ocorrencia', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo de dúvida',
                'verbose_name_plural': 'Grupos de dúvida',
                'ordering': ['-frequencia'],
                'indexes': [models.Index(fields=['assunto', 'texto_normalizado'], name='analytics_g_assunto_a54788_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerguntaRegistrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('texto_normalizado', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('assunto', models.CharField(blank=True, choices=[('direito', 'Direito eleitoral'), ('contabilidade', 'Contabilidade eleitoral'), ('impulsionamento', 'Impulsionamento eleitoral')], default='', max_length=20)),
                ('on_topic', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas', to='analytics.grupoduvida')),
            ],
            options={
                'verbose_name': 'Pergunta registrada',
                'verbose_name_plural': 'Perguntas registradas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
