# Generated by Django 5.1.15 on 2026-07-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoLLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=60)),
                ('tarefa', models.CharField(max_length=20)),
                ('tokens_entrada', models.PositiveIntegerField(default=0)),
                ('tokens_saida', models.PositiveIntegerField(default=0)),
                ('custo_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'consumo de LLM',
                'verbose_name_plural': 'consumos de LLM',
                'ordering': ['-criado_em'],
            },
        ),
    ]
