# Generated by Django 5.1.15 on 2026-07-09 17:55

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # CREATE EXTENSION vector — no-op fora do Postgres (Django ignora).
        VectorExtension(),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='título/identificação')),
                ('tipo', models.CharField(choices=[('norma', 'Norma (lei/resolução)'), ('jurisprudencia', 'Jurisprudência (TSE/TREs)'), ('doutrina', 'Doutrina'), ('curso', 'Curso/apostila'), ('anexo', 'Anexo interno')], max_length=20)),
                ('assunto', models.CharField(choices=[('direito', 'Direito eleitoral'), ('contabilidade', 'Contabilidade eleitoral'), ('impulsionamento', 'Impulsionamento eleitoral')], max_length=20)),
                ('citavel', models.BooleanField(default=False, verbose_name='citável como fonte?')),
                ('vigente', models.BooleanField(default=True, verbose_name='vigente/válido?')),
                ('vigencia_inicio', models.DateField(blank=True, null=True)),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('fonte_url', models.URLField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Trecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('conteudo', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='rag.documento')),
            ],
            options={
                'ordering': ['documento', 'ordem'],
            },
        ),
    ]
