# Generated by Django 5.1.15 on 2026-07-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='conteudo_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
