# Generated by Django 5.1.15 on 2026-07-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_documento_conteudo_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='origem',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='origem_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='documento',
            name='subtema',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
