# Generated by Django 5.1.15 on 2026-07-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_documento_origem_documento_origem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='texto_extraido',
            field=models.TextField(blank=True, default=''),
        ),
    ]
