# Generated by Django 5.1.15 on 2026-07-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0005_trecho_indice_hnsw'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='ocr_completo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='ocr_paginas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
